apiVersion: eaas.envmgmt.io/v1
kind: WorkflowHandler
metadata:
  name: em-wh
  project: mdp
spec:
  config:
    function:
      language: python
      name: em-wh
      skipBuild: false
      source: "from typing import *\nfrom logging import Logger\n\ndef handle(logger:
        Logger,request: Dict[str, Any]) -> Dict[str, Any]:\n  logger.info(f\"inside
        function handler, request: {request}\", extra={\"request\": request})\n\t\n
        \ logger.info(\"Hello world... \")\n\t\n  return {\n    \"output\": \"Hello
        world\"\n  }\n"
      targetPlatforms:
      - linux/amd64
    type: function