apiVersion: eaas.envmgmt.io/v1
kind: WorkflowHandler
metadata:
  name: em-wh
  project: mdp
spec:
  config:
    function:
      language: python
      name: em-wh
      skipBuild: false
      source: |
        from typing import Dict, Any
        from logging import Logger

        def handle(logger: Logger, request: Dict[str, Any]) -> Dict[str, Any]:
            logger.info(f"inside function handler, request: {request}", extra={"request": request})
            logger.info("Hello world... ")
            return {
                "output": "Hello world"
            }
      targetPlatforms:
        - linux/amd64
    type: function
